### ISSUE TITLE
Volume change

### ISSUE THREAD

**Issue by rootcli** [lawrencesystems/graylog#8]
Hi,
I am trying to change the volume for the opensearch.
to:
```
volumes:
      - "/mnt/logs-data/log_data:/usr/share/opensearch/data"
```
but keep getting access issue in the graylog docker container because it is connected to :
```
volumes:
  mongo_data:
    driver: local
  log_data:
    driver: local
  graylog_data:
    driver: local
```

Any help is most appreciated 🙏
